version: '3'
services:
  mariadb:
    image: mariadb:10.1
    container_name:trombinoscopemaster_mariadb_1
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=simplon
      - MYSQL_USER=simplon
      - MYSQL_PASSWORD=simplon
    ports:
      - "3307:3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
          - mariadb:mariadb
      ports:
          - 8001:80
      environment:
          PMA_HOST: mariadb
          PMA_PORT: 3306
          
  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    links:
        - mariadb
    environment: 
      - MYSQL_HOST=mariadb

  sass:
    image: "node:10"
    working_dir: /application
    volumes:
      - ./:/application
    ports:
      - "8000:8000"
    command: >
      bash -c "npm install node-sass --save
      && ./node_modules/.bin/node-sass scss -o  public-html/css -w --source-map public-html/css"


  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
